package com.triocodes.medivision.Enum;

/**
 * Created by admin on 02-05-16.
 */
public enum  ServiceCallEnum {
    ONDUTY,ONDUTYCHECK,OFFDUTY,JOURNEYCHECKFROMCLOCKIN,JOURNEY,DESTINATION,TASK,JOURNEYCHECK,DUTYREPORT,DOCTORSSPINNER,DOCTORSVISIT,
    TASKSTATUSSPINNER,TASKSTATUSSAVE,MEETREPORT,JOURNEYREPORT;
}
